#!/usr/bin/env bash

_taufiq_autocomplete (){
 local category=""
 local catAt=0
 local command=""
 local cmdAt=0
 for ((i=1; i<=COMP_CWORD; i++)); do
	local CWord="${COMP_WORDS[i]}"
	if [[ "$CWord" == "-"* ]]; then
		continue
	fi
 	if [[ -z "${category}" ]] then
		category="$CWord"
		catAt="$i"
	elif [[ -z "${command}" ]] then
		command="$CWord"
		cmdAt="$i"
	fi
 done

 if [[ "$catAt" -eq "$COMP_CWORD" ]] then
	COMPREPLY=($(cd "$MY_SCRIPTS" && ls -d */ | grep "^${category}" | tr -d '/'))
elif [[ "$COMP_CWORD" -eq "$cmdAt" && -n "$category" && -d "$MY_SCRIPTS/$category" ]]; then
	COMPREPLY=($(ls "$MY_SCRIPTS/$category" | grep "^${command}"))
fi
}

complete -F _taufiq_autocomplete taufiq
