#!/bin/bash

getArgs() {	
	category=""
	command=""
	flag=""
	for arg in "$@"; do
		if [[ "$arg" == "-"* ]]; then
			flag=$(echo "$arg"|tr -d -) 
		elif [[ -z "${category}" ]] then
			category="$arg"
		elif [[ -z "${command}" ]] then
			command="$arg"
		fi
	done
    if [[ -z "$flag" ]]; then
        # allow fast shortcut e.g. taufiq hyprland start > taufiq h s (assuming no other h category and s command inside the hyprland category)
        if [[ ! -d "$MY_SCRIPTS/$category" && 
            $(cd "$MY_SCRIPTS" && ls -d1A */ | grep "^$category" | wc -l) -eq 1 ]]
        then
            category=$(cd "$MY_SCRIPTS" && ls -d1A */ | grep "^$category" | tr -d /)
        fi    
        if [[ ! -e "$MY_SCRIPTS/$category/$command" && 
            $(cd "$MY_SCRIPTS/$category" && ls -1A * | grep "^$command" | wc -l) -eq 1 ]]
        then
            command=$(cd "$MY_SCRIPTS/$category" && ls -1A * | grep "^$command")
        fi
    fi

	script="$MY_SCRIPTS/$category/${command}"
	if [[ "$flag" == "a" && -n "$category" && -n "$command" ]]; then
		create "$category" "$command"	
	elif [[ "$flag" == "r" ]]; then
		if [[ -n "$command" ]]; then
			rm "$script"
		elif [[ -n "$category" ]]; then
			rmdir "$MY_SCRIPTS/$category/"
		fi
	else
		execute "$script"
	fi
}

create(){
	[[ -d "$MY_SCRIPTS/$1" ]] || mkdir "$MY_SCRIPTS/$1"
	[[ -e "$MY_SCRIPTS/$1/$2" ]] || touch "$MY_SCRIPTS/$1/$2" && chmod +x "$MY_SCRIPTS/$1/$2"
    nvim "$MY_SCRIPTS/$1/$2"
}

execute(){
	if [[ -n "$command" && -n "$category" ]]; then
	if [ -x "$script" ]; then
	  "$1"
	else
	  echo "Command not found: $category/$command"
	fi
	else
	  echo "Must be 2 command"
	fi
}

getArgs "$@"

